### ISSUE TITLE
Negatives values using time-random-linear-interpolator

### ISSUE THREAD

**Issue by cayetanobv** [gtorodelvalle/fiware-device-simulator#117]
Hi again team,

When using time-random-linear-interpolator and last x-axis value (24) value is not included and previous (and actually the last) x-axis value is 0, simulation gives negative numbers. 

Tested example (with available parking spots):
```
"time-random-linear-interpolator([[0,0],[7,0],[8,random(0,30)],[14,random(50,100)],[16,100],[18,random(60,100)],[22,random(30,80)],[23,0]])"
```
Between 23:00 and 23:59 hours values are always negative. 

I think this is not exactly a bug, but I have reported you to take it in mind (and maybe ... can we add a remark in docs?).

Thanks!

**Comment by gtorodelvalle** [comment]
Hi @cayetanobv ! Yeah, the behaviour is the expected since we use the https://www.npmjs.com/package/linear-interpolator package for the linear interpolation and since the value for the 23th hour is 0 and the previous entry was possitive, the "line" goes below 0... :)

Not to limit the scenarios where this (time-random-linear-interpolator) and the time-linear-interpolator is used, I think I'll opt for the option you mention in your message regarding properly documenting this behaviour... :) I'll include you as the reviewer as soon as I send the PR... :)

Thank you very much!

**Comment by cayetanobv** [comment]
LGTM. Thanks!
